# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6qcDTYVVPsCvjUg2F86UYAR138Hq1X0
"""

import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

# Configuración de estilo para gráficos
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# ============================================================================
# 1. CARGA Y LIMPIEZA DE DATOS
# ============================================================================

# Cargar datos
df = pd.read_csv('PCOS_data_1.csv')

print("=" * 80)
print("ANÁLISIS DESCRIPTIVO DE BIOMARCADORES Y FACTORES ASOCIADOS AL SOP")
print("Equipo: Los SOP-timizadores")
print(f"Fecha: {datetime.now().strftime('%d-%m-%Y')}")
print("=" * 80)

# Crear columna FSH/LH ratio si no existe
if 'FSH/LH' not in df.columns:
    df['FSH/LH'] = df['FSH(mIU/mL)'] / df['LH(mIU/mL)']

# Separar grupos
df_sop = df[df['PCOS (Y/N)'] == 1]
df_no_sop = df[df['PCOS (Y/N)'] == 0]

print(f"\n📊 DISTRIBUCIÓN DE LA MUESTRA:")
print(f"   • Total de participantes: {len(df)}")
print(f"   • Con SOP: {len(df_sop)} ({len(df_sop)/len(df)*100:.1f}%)")
print(f"   • Sin SOP: {len(df_no_sop)} ({len(df_no_sop)/len(df)*100:.1f}%)")

# ============================================================================
# 2. DEFINIR VARIABLES DE INTERÉS
# ============================================================================

variables_continuas = {
    'Antropométricas': ['BMI', 'Waist:Hip Ratio'],
    'Foliculares': ['Follicle No. (L)', 'Follicle No. (R)',
                    'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)'],
    'Hormonales': ['FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH',
                   'AMH(ng/mL)', 'PRG(ng/mL)', 'PRL(ng/mL)', 'TSH (mIU/L)']
}

variables_categoricas = [
    'Weight gain(Y/N)', 'hair growth(Y/N)', 'Skin darkening (Y/N)',
    'Hair loss(Y/N)', 'Pimples(Y/N)', 'Fast food (Y/N)', 'Reg.Exercise(Y/N)'
]

# ============================================================================
# 3. ANÁLISIS DESCRIPTIVO - VARIABLES CONTINUAS
# ============================================================================

def calcular_estadisticos(grupo):
    """Calcula estadísticos descriptivos para un grupo"""
    return {
        'n': grupo.count(),
        'media': grupo.mean(),
        'mediana': grupo.median(),
        'de': grupo.std(),
        'min': grupo.min(),
        'max': grupo.max(),
        'q1': grupo.quantile(0.25),
        'q3': grupo.quantile(0.75),
        'cv': (grupo.std() / grupo.mean() * 100) if grupo.mean() != 0 else np.nan
    }

print("\n" + "=" * 80)
print("ANÁLISIS DESCRIPTIVO - VARIABLES CONTINUAS")
print("=" * 80)

resultados_continuas = {}

for categoria, variables in variables_continuas.items():
    print(f"\n{'─' * 80}")
    print(f"📈 {categoria.upper()}")
    print(f"{'─' * 80}")

    for var in variables:
        if var in df.columns:
            print(f"\n{var}:")

            # Calcular estadísticos para ambos grupos
            stats_sop = calcular_estadisticos(df_sop[var])
            stats_no_sop = calcular_estadisticos(df_no_sop[var])

            # Almacenar resultados
            resultados_continuas[var] = {
                'Con SOP': stats_sop,
                'Sin SOP': stats_no_sop
            }

            # Imprimir resultados
            print(f"  CON SOP (n={stats_sop['n']:.0f}):")
            print(f"    Media: {stats_sop['media']:.2f} ± {stats_sop['de']:.2f}")
            print(f"    Mediana: {stats_sop['mediana']:.2f}")
            print(f"    Rango: [{stats_sop['min']:.2f} - {stats_sop['max']:.2f}]")
            print(f"    IQR: [{stats_sop['q1']:.2f} - {stats_sop['q3']:.2f}]")
            print(f"    CV: {stats_sop['cv']:.1f}%")

            print(f"  SIN SOP (n={stats_no_sop['n']:.0f}):")
            print(f"    Media: {stats_no_sop['media']:.2f} ± {stats_no_sop['de']:.2f}")
            print(f"    Mediana: {stats_no_sop['mediana']:.2f}")
            print(f"    Rango: [{stats_no_sop['min']:.2f} - {stats_no_sop['max']:.2f}]")
            print(f"    IQR: [{stats_no_sop['q1']:.2f} - {stats_no_sop['q3']:.2f}]")
            print(f"    CV: {stats_no_sop['cv']:.1f}%")

            # Diferencia de medias
            diff = stats_sop['media'] - stats_no_sop['media']
            diff_pct = (diff / stats_no_sop['media'] * 100) if stats_no_sop['media'] != 0 else np.nan
            print(f"  DIFERENCIA: {diff:+.2f} ({diff_pct:+.1f}%)")

# ============================================================================
# 4. ANÁLISIS DESCRIPTIVO - VARIABLES CATEGÓRICAS
# ============================================================================

print("\n" + "=" * 80)
print("ANÁLISIS DESCRIPTIVO - VARIABLES CATEGÓRICAS")
print("=" * 80)

resultados_categoricas = {}

for var in variables_categoricas:
    if var in df.columns:
        print(f"\n{'─' * 80}")
        print(f"📊 {var}")
        print(f"{'─' * 80}")

        # Tablas de contingencia
        tabla_sop = df_sop[var].value_counts()
        tabla_no_sop = df_no_sop[var].value_counts()

        # Para SOP
        n_si_sop = tabla_sop.get(1, 0)
        n_total_sop = len(df_sop[df_sop[var].notna()])
        pct_si_sop = (n_si_sop / n_total_sop * 100) if n_total_sop > 0 else 0

        # Para No SOP
        n_si_no_sop = tabla_no_sop.get(1, 0)
        n_total_no_sop = len(df_no_sop[df_no_sop[var].notna()])
        pct_si_no_sop = (n_si_no_sop / n_total_no_sop * 100) if n_total_no_sop > 0 else 0

        resultados_categoricas[var] = {
            'Con SOP': {'Si': n_si_sop, 'No': n_total_sop - n_si_sop,
                       'Total': n_total_sop, 'Porcentaje_Si': pct_si_sop},
            'Sin SOP': {'Si': n_si_no_sop, 'No': n_total_no_sop - n_si_no_sop,
                       'Total': n_total_no_sop, 'Porcentaje_Si': pct_si_no_sop}
        }

        print(f"  CON SOP (n={n_total_sop}):")
        print(f"    Sí: {n_si_sop} ({pct_si_sop:.1f}%)")
        print(f"    No: {n_total_sop - n_si_sop} ({100-pct_si_sop:.1f}%)")

        print(f"  SIN SOP (n={n_total_no_sop}):")
        print(f"    Sí: {n_si_no_sop} ({pct_si_no_sop:.1f}%)")
        print(f"    No: {n_total_no_sop - n_si_no_sop} ({100-pct_si_no_sop:.1f}%)")

        print(f"  DIFERENCIA: {pct_si_sop - pct_si_no_sop:+.1f} puntos porcentuales")

# ============================================================================
# 5. VISUALIZACIONES
# ============================================================================

print("\n" + "=" * 80)
print("GENERANDO VISUALIZACIONES...")
print("=" * 80)

# 5.1 Boxplots para variables hormonales clave
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Comparación de Biomarcadores Hormonales: SOP vs No-SOP',
             fontsize=16, fontweight='bold')

hormonas_clave = ['AMH(ng/mL)', 'LH(mIU/mL)', 'FSH/LH', 'TSH (mIU/L)']

for idx, var in enumerate(hormonas_clave):
    ax = axes[idx // 2, idx % 2]
    data_plot = df[[var, 'PCOS (Y/N)']].dropna()

    bp = ax.boxplot([data_plot[data_plot['PCOS (Y/N)'] == 0][var],
                     data_plot[data_plot['PCOS (Y/N)'] == 1][var]],
                    labels=['Sin SOP', 'Con SOP'],
                    patch_artist=True,
                    notch=True)

    bp['boxes'][0].set_facecolor('#90EE90')
    bp['boxes'][1].set_facecolor('#FFB6C6')

    ax.set_ylabel(var, fontweight='bold')
    ax.set_title(f'{var}')
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('boxplots_hormonas.png', dpi=300, bbox_inches='tight')
print("✓ Guardado: boxplots_hormonas.png")

# 5.2 Histogramas comparativos para BMI y Waist:Hip Ratio
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Distribución de Variables Antropométricas',
             fontsize=16, fontweight='bold')

vars_antro = ['BMI', 'Waist:Hip Ratio']

for idx, var in enumerate(vars_antro):
    ax = axes[idx]

    df_no_sop[var].dropna().hist(ax=ax, bins=20, alpha=0.6,
                                  label='Sin SOP', color='green', edgecolor='black')
    df_sop[var].dropna().hist(ax=ax, bins=20, alpha=0.6,
                               label='Con SOP', color='red', edgecolor='black')

    ax.set_xlabel(var, fontweight='bold')
    ax.set_ylabel('Frecuencia')
    ax.set_title(f'Distribución de {var}')
    ax.legend()
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('histogramas_antropometria.png', dpi=300, bbox_inches='tight')
print("✓ Guardado: histogramas_antropometria.png")

# 5.3 Gráfico de barras para síntomas clínicos
sintomas_plot = ['Weight gain(Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)',
                 'hair growth(Y/N)', 'Skin darkening (Y/N)']

pct_sop = []
pct_no_sop = []
labels = []

for var in sintomas_plot:
    if var in df.columns:
        labels.append(var.replace('(Y/N)', ''))
        pct_sop.append(resultados_categoricas[var]['Con SOP']['Porcentaje_Si'])
        pct_no_sop.append(resultados_categoricas[var]['Sin SOP']['Porcentaje_Si'])

x = np.arange(len(labels))
width = 0.35

fig, ax = plt.subplots(figsize=(12, 6))
ax.bar(x - width/2, pct_no_sop, width, label='Sin SOP', color='#90EE90', edgecolor='black')
ax.bar(x + width/2, pct_sop, width, label='Con SOP', color='#FFB6C6', edgecolor='black')

ax.set_ylabel('Porcentaje (%)', fontweight='bold')
ax.set_title('Prevalencia de Síntomas Clínicos: Comparación SOP vs No-SOP',
             fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(labels, rotation=45, ha='right')
ax.legend()
ax.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig('barras_sintomas.png', dpi=300, bbox_inches='tight')
print("✓ Guardado: barras_sintomas.png")

# 5.4 Heatmap de correlaciones para grupo SOP
vars_correlacion = ['BMI', 'AMH(ng/mL)', 'LH(mIU/mL)', 'FSH(mIU/mL)',
                    'FSH/LH', 'TSH (mIU/L)', 'Waist:Hip Ratio']

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Con SOP
corr_sop = df_sop[vars_correlacion].corr()
sns.heatmap(corr_sop, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, ax=axes[0], cbar_kws={'label': 'Correlación'})
axes[0].set_title('Matriz de Correlación - Con SOP', fontweight='bold')

# Sin SOP
corr_no_sop = df_no_sop[vars_correlacion].corr()
sns.heatmap(corr_no_sop, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, ax=axes[1], cbar_kws={'label': 'Correlación'})
axes[1].set_title('Matriz de Correlación - Sin SOP', fontweight='bold')

plt.tight_layout()
plt.savefig('heatmap_correlaciones.png', dpi=300, bbox_inches='tight')
print("✓ Guardado: heatmap_correlaciones.png")

# ============================================================================
# 6. GENERAR DOCUMENTO MARKDOWN
# ============================================================================

print("\n" + "=" * 80)
print("GENERANDO DOCUMENTO MARKDOWN...")
print("=" * 80)

with open('Reporte_Analisis_Descriptivo_SOP.md', 'w', encoding='utf-8') as f:
    f.write("# ANÁLISIS DESCRIPTIVO DE BIOMARCADORES Y FACTORES ASOCIADOS AL SOP\n\n")
    f.write("**Síndrome de Ovario Poliquístico (SOP)**\n\n")
    f.write(f"**Equipo:** Los SOP-timizadores  \n")
    f.write(f"**Integrantes:** Paul Duran Roldan, Francisco Adonai Ortega Leos  \n")
    f.write(f"**Fecha:** {datetime.now().strftime('%d de %B de %Y')}  \n")
    f.write(f"**Materia:** Probabilidad y Estadística  \n\n")

    f.write("---\n\n")

    # Resumen ejecutivo
    f.write("## RESUMEN EJECUTIVO\n\n")
    f.write("Este análisis descriptivo exploratorio examina las diferencias en biomarcadores ")
    f.write("hormonales, variables antropométricas y síntomas clínicos entre mujeres con y ")
    f.write("sin diagnóstico de Síndrome de Ovario Poliquístico (SOP).\n\n")

    f.write(f"- **Tamaño de muestra total:** {len(df)} participantes\n")
    f.write(f"- **Mujeres con SOP:** {len(df_sop)} ({len(df_sop)/len(df)*100:.1f}%)\n")
    f.write(f"- **Mujeres sin SOP:** {len(df_no_sop)} ({len(df_no_sop)/len(df)*100:.1f}%)\n\n")

    # Tabla resumen de variables continuas
    f.write("---\n\n")
    f.write("## 1. ANÁLISIS DE VARIABLES CONTINUAS\n\n")

    for categoria, variables in variables_continuas.items():
        f.write(f"### 1.{list(variables_continuas.keys()).index(categoria)+1} {categoria}\n\n")

        for var in variables:
            if var in resultados_continuas:
                stats_sop = resultados_continuas[var]['Con SOP']
                stats_no_sop = resultados_continuas[var]['Sin SOP']

                f.write(f"#### **{var}**\n\n")
                f.write("| Estadístico | Con SOP | Sin SOP | Diferencia |\n")
                f.write("|------------|---------|---------|------------|\n")
                f.write(f"| **n** | {stats_sop['n']:.0f} | {stats_no_sop['n']:.0f} | - |\n")
                f.write(f"| **Media** | {stats_sop['media']:.2f} | {stats_no_sop['media']:.2f} | ")
                diff = stats_sop['media'] - stats_no_sop['media']
                f.write(f"{diff:+.2f} |\n")
                f.write(f"| **Mediana** | {stats_sop['mediana']:.2f} | {stats_no_sop['mediana']:.2f} | ")
                f.write(f"{stats_sop['mediana'] - stats_no_sop['mediana']:+.2f} |\n")
                f.write(f"| **DE** | {stats_sop['de']:.2f} | {stats_no_sop['de']:.2f} | - |\n")
                f.write(f"| **Mín - Máx** | {stats_sop['min']:.2f} - {stats_sop['max']:.2f} | ")
                f.write(f"{stats_no_sop['min']:.2f} - {stats_no_sop['max']:.2f} | - |\n")
                f.write(f"| **Q1 - Q3** | {stats_sop['q1']:.2f} - {stats_sop['q3']:.2f} | ")
                f.write(f"{stats_no_sop['q1']:.2f} - {stats_no_sop['q3']:.2f} | - |\n")
                f.write(f"| **CV (%)** | {stats_sop['cv']:.1f}% | {stats_no_sop['cv']:.1f}% | - |\n\n")

                # Interpretación
                f.write("**Interpretación:**  \n")
                if abs(diff) > stats_no_sop['de']:
                    f.write(f"Se observa una diferencia notable de {abs(diff):.2f} unidades entre grupos. ")
                    if diff > 0:
                        f.write(f"Las mujeres con SOP presentan valores **más elevados** de {var}. ")
                    else:
                        f.write(f"Las mujeres con SOP presentan valores **más bajos** de {var}. ")
                else:
                    f.write(f"La diferencia entre grupos ({diff:.2f}) es menor que una desviación estándar, ")
                    f.write("sugiriendo valores similares entre ambas poblaciones. ")
                f.write("\n\n")

    # Variables categóricas
    f.write("---\n\n")
    f.write("## 2. ANÁLISIS DE VARIABLES CATEGÓRICAS\n\n")
    f.write("### 2.1 Síntomas Clínicos y Factores de Estilo de Vida\n\n")

    f.write("| Variable | Con SOP (%) | Sin SOP (%) | Diferencia (pp) |\n")
    f.write("|----------|-------------|-------------|------------------|\n")

    for var in variables_categoricas:
        if var in resultados_categoricas:
            pct_sop = resultados_categoricas[var]['Con SOP']['Porcentaje_Si']
            pct_no_sop = resultados_categoricas[var]['Sin SOP']['Porcentaje_Si']
            diff = pct_sop - pct_no_sop

            nombre_limpio = var.replace('(Y/N)', '').strip()
            f.write(f"| **{nombre_limpio}** | {pct_sop:.1f}% | {pct_no_sop:.1f}% | {diff:+.1f} |\n")

    f.write("\n**Nota:** pp = puntos porcentuales\n\n")

    # Conclusiones principales
    f.write("---\n\n")
    f.write("## 3. HALLAZGOS PRINCIPALES\n\n")

    # Identificar diferencias más notables
    f.write("### 3.1 Variables con Mayor Diferencia Entre Grupos\n\n")
    f.write("**Variables Continuas:**\n\n")

    # Calcular diferencias porcentuales para todas las variables
    diffs_continuas = []
    for var, stats in resultados_continuas.items():
        media_sop = stats['Con SOP']['media']
        media_no_sop = stats['Sin SOP']['media']
        if media_no_sop != 0:
            diff_pct = abs((media_sop - media_no_sop) / media_no_sop * 100)
            diffs_continuas.append((var, diff_pct, media_sop - media_no_sop))

    diffs_continuas.sort(key=lambda x: x[1], reverse=True)

    for idx, (var, diff_pct, diff_abs) in enumerate(diffs_continuas[:5], 1):
        direccion = "mayor" if diff_abs > 0 else "menor"
        f.write(f"{idx}. **{var}**: {diff_pct:.1f}% de diferencia ({direccion} en grupo con SOP)\n")

    f.write("\n**Variables Categóricas:**\n\n")

    diffs_categoricas = []
    for var, stats in resultados_categoricas.items():
        diff = abs(stats['Con SOP']['Porcentaje_Si'] - stats['Sin SOP']['Porcentaje_Si'])
        diffs_categoricas.append((var, diff, stats['Con SOP']['Porcentaje_Si'] - stats['Sin SOP']['Porcentaje_Si']))

    diffs_categoricas.sort(key=lambda x: x[1], reverse=True)

    for idx, (var, diff, diff_signed) in enumerate(diffs_categoricas[:5], 1):
        nombre_limpio = var.replace('(Y/N)', '').strip()
        direccion = "más prevalente" if diff_signed > 0 else "menos prevalente"
        f.write(f"{idx}. **{nombre_limpio}**: {diff:.1f} puntos porcentuales de diferencia ")
        f.write(f"({direccion} en grupo con SOP)\n")

    # Conclusiones finales
    f.write("\n### 3.2 Conclusiones del Análisis Descriptivo\n\n")
    f.write("1. **Perfil Hormonal:** Las mujeres con SOP muestran diferencias significativas en ")
    f.write("biomarcadores hormonales clave, particularmente en AMH, LH y la relación FSH/LH.\n\n")

    f.write("2. **Características Antropométricas:** Se observan diferencias en el IMC y la ")
    f.write("relación cintura-cadera entre los grupos, sugiriendo un componente metabólico ")
    f.write("asociado al SOP.\n\n")

    f.write("3. **Síntomas Clínicos:** Existe una mayor prevalencia de síntomas como acné, ")
    f.write("ganancia de peso y caída de cabello en el grupo con SOP.\n\n")

    f.write("4. **Características Foliculares:** El número de folículos y su tamaño promedio ")
    f.write("difieren notablemente entre grupos, consistente con el diagnóstico de SOP.\n\n")

    # Visualizaciones
    f.write("---\n\n")
    f.write("## 4. VISUALIZACIONES\n\n")
    f.write("Las siguientes visualizaciones fueron generadas para facilitar la interpretación de los resultados:\n\n")
    f.write("1. **boxplots_hormonas.png** - Comparación de biomarcadores hormonales mediante diagramas de caja\n")
    f.write("2. **histogramas_antropometria.png** - Distribución de variables antropométricas\n")
    f.write("3. **barras_sintomas.png** - Prevalencia de síntomas clínicos\n")
    f.write("4. **heatmap_correlaciones.png** - Matrices de correlación para ambos grupos\n\n")

    # Próximos pasos
    f.write("---\n\n")
    f.write("## 5. PRÓXIMOS PASOS\n\n")
    f.write("Con base en este análisis descriptivo, los siguientes análisis están programados:\n\n")
    f.write("1. **Pruebas de hipótesis** (t-test/Mann-Whitney) para variables continuas\n")
    f.write("2. **Pruebas Chi-cuadrado** para variables categóricas\n")
    f.write("3. **ANOVA** para evaluar efectos de síntomas en hormonas\n")
    f.write("4. **Cálculo de Odds Ratios** para cuantificar riesgo de síntomas\n")
    f.write("5. **Probabilidades condicionales** mediante Teorema de Bayes\n\n")

    # Referencias
    f.write("---\n\n")
    f.write("## INFORMACIÓN DEL ANÁLISIS\n\n")
    f.write(f"- **Fecha de análisis:** {datetime.now().strftime('%d/%m/%Y %H:%M')}\n")
    f.write(f"- **Software:** Python 3.x con pandas, numpy, scipy, matplotlib, seaborn\n")
    f.write(f"- **Datos:** PCOS_data_1.csv ({len(df)} registros)\n")

print("✓ Guardado: Reporte_Analisis_Descriptivo_SOP.md")

print("\n" + "=" * 80)
print("✅ ANÁLISIS COMPLETADO EXITOSAMENTE")
print("=" * 80)
print("\nArchivos generados:")
print("  1. Reporte_Analisis_Descriptivo_SOP.md (Documento completo)")
print("  2. boxplots_hormonas.png")
print("  3. histogramas_antropometria.png")
print("  4. barras_sintomas.png")
print("  5. heatmap_correlaciones.png")
print("\n" + "=" * 80)

"""## Resumen de Proporciones por Grupo (Sin SOP vs Con SOP)

Aquí se presenta un resumen numérico de las principales diferencias observadas entre el grupo de mujeres sin SOP y el grupo con SOP, basado en el análisis descriptivo:

| Característica             | Sin SOP (Media / %) | Con SOP (Media / %) | Diferencia (Absoluta / pp) |
|----------------------------|--------------------|--------------------|----------------------------|
| **Variables Continuas**    |                    |                    |                            |
| BMI (Media)                | 23.74              | 25.47              | +1.72                      |
| Waist:Hip Ratio (Media)    | 0.89               | 0.89               | +0.00                      |
| Follicle No. (L) (Media)   | 4.35               | 9.79               | +5.43                      |
| Follicle No. (R) (Media)   | 4.64               | 10.76              | +6.13                      |
| Avg. F size (L) (mm) (Media)| 14.69              | 15.70              | +1.01                      |
| Avg. F size (R) (mm) (Media)| 15.23              | 15.92              | +0.69                      |
| FSH(mIU/mL) (Media)        | 19.19              | 5.17               | -14.01                     |
| LH(mIU/mL) (Media)         | 2.61               | 14.40              | +11.79                     |
| FSH/LH (Media)             | 7.68               | 5.31               | -2.37                      |
| AMH(ng/mL) (Media)         | 4.54               | 7.84               | +3.30                      |
| PRG(ng/mL) (Media)         | 0.73               | 0.37               | -0.36                      |
| PRL(ng/mL) (Media)         | 24.27              | 24.43              | +0.16                      |
| TSH (mIU/L) (Media)        | 3.01               | 2.93               | -0.08                      |
| **Variables Categóricas**  |                    |                    |                            |
| Weight gain(Y/N) (%)       | 22.8%              | 68.4%              | +45.6 pp                   |
| hair growth(Y/N) (%)       | 12.9%              | 57.1%              | +44.2 pp                   |
| Skin darkening (Y/N) (%)   | 15.4%              | 62.1%              | +46.8 pp                   |
| Hair loss(Y/N) (%)         | 39.3%              | 57.6%              | +18.3 pp                   |
| Pimples(Y/N) (%)           | 39.0%              | 69.5%              | +30.5 pp                   |
| Fast food (Y/N) (%)        | 38.3%              | 78.5%              | +40.2 pp                   |
| Reg.Exercise(Y/N) (%)      | 22.8%              | 28.8%              | +6.0 pp                    |

**Nota:** Las diferencias para variables continuas son las diferencias de medias. Las diferencias para variables categóricas son las diferencias en puntos porcentuales (pp) de la prevalencia del "Sí".

## Análisis Descriptivo Detallado: Perspectiva Ampliada sobre el SOP

Este análisis se fundamenta en los datos procesados y presenta una interpretación más profunda de las diferencias observadas entre mujeres con y sin Síndrome de Ovario Poliquístico (SOP). La muestra de 541 participantes, con aproximadamente un tercio diagnosticado con SOP, nos permite vislumbrar patrones importantes asociados a esta condición.

### Explorando las Diferencias y su Contexto

Al comparar los grupos, ciertos hallazgos destacan de manera significativa, arrojando luz sobre las características distintivas del SOP:

- **Características Foliculares Anormales:** Uno de los indicadores más notables del SOP es la morfología ovárica. Nuestros resultados muestran consistentemente un **número de folículos (tanto en el ovario izquierdo como en el derecho)** que es más del doble en las mujeres con SOP en comparación con aquellas sin el síndrome. Esto se alinea perfectamente con el criterio diagnóstico de ovarios poliquísticos en la ecografía, un sello distintivo del SOP.

- **Desbalance Hormonal Clave:** El perfil hormonal en el SOP a menudo presenta alteraciones significativas. En este análisis, la **Hormona Luteinizante (LH)** se eleva drásticamente en el grupo con SOP, superando en más de cuatro veces los niveles del grupo sin SOP. De manera similar, la **Hormona Antimulleriana (AMH)**, un marcador de la reserva ovárica que también refleja la actividad de los folículos pequeños, se encuentra notablemente incrementada en las mujeres con SOP, casi duplicando los niveles del grupo sin SOP. Si bien la **Hormona Folículo Estimulante (FSH)** no muestra una diferencia tan marcada en la media, el desbalance se hace evidente en la **relación FSH/LH**, que tiende a ser menor en el grupo con SOP, un patrón clásico en la endocrinología del SOP.

- **Implicaciones Antropométricas y Metabólicas:** Las mujeres con SOP a menudo enfrentan desafíos relacionados con el peso y el metabolismo. Observamos que el **Índice de Masa Corporal (BMI)** es consistentemente más alto en el grupo con SOP. Aunque la diferencia promedio puede parecer modesta, refuerza la conocida asociación entre el SOP y una mayor predisposición al sobrepeso y la obesidad, que a su vez pueden exacerbar otros aspectos del síndrome.

- **Manifestaciones Clínicas Cutáneas y Sistémicas:** Los síntomas visibles son una parte crucial del cuadro clínico del SOP. Nuestros datos confirman que las mujeres con SOP experimentan una prevalencia significativamente mayor de síntomas como el **oscurecimiento de la piel**, el **crecimiento excesivo de vello (hirsutismo)** y el **acné**. Estas manifestaciones suelen estar relacionadas con los niveles elevados de andrógenos (hormonas masculinas) que son comunes en el SOP. La **ganancia de peso** también es un síntoma reportado con mucha mayor frecuencia en este grupo, en línea con las observaciones sobre el BMI.

- **Consideraciones sobre el Estilo de Vida:** Si bien no es un síntoma directo, la mayor prevalencia reportada del consumo de **comida rápida** en el grupo con SOP podría ser un factor contribuyente o un indicador de patrones de estilo de vida que impactan la salud metabólica y hormonal.

En síntesis, este análisis descriptivo valida y visualiza las características fundamentales del SOP: la presencia de ovarios con múltiples folículos, un perfil hormonal alterado con elevaciones de LH y AMH, una mayor tendencia al sobrepeso, y la manifestación de síntomas androgénicos y metabólicos. Estos hallazgos refuerzan la complejidad del SOP y la interconexión de sus diversas manifestaciones, sentando las bases para investigaciones más profundas, incluyendo análisis inferenciales y predictivos.
"""