# -*- coding: utf-8 -*-
"""Anova2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtgum04-C5nLOo_AnKoffp-cBEBYxZ6p
"""

import pandas as pd
import scipy.stats as stats

# Cargar el dataset
pcos_data = pd.read_csv('/content/PCOS_data.csv')

# Seleccionar columnas relevantes
fast_food = pcos_data['Fast food (Y/N)']
fsh = pcos_data['FSH(mIU/mL)']
lh = pcos_data['LH(mIU/mL)']
fsh_lh_ratio = pcos_data['FSH/LH']

# Separar datos en dos grupos: "Fast food = Yes" y "Fast food = No"
fast_food_yes = pcos_data[fast_food == 1]
fast_food_no = pcos_data[fast_food == 0]

# Realizar ANOVA para FSH, LH y la relación FSH/LH
anova_fsh = stats.f_oneway(fast_food_yes['FSH(mIU/mL)'], fast_food_no['FSH(mIU/mL)'])
anova_lh = stats.f_oneway(fast_food_yes['LH(mIU/mL)'], fast_food_no['LH(mIU/mL)'])
anova_fsh_lh = stats.f_oneway(fast_food_yes['FSH/LH'], fast_food_no['FSH/LH'])

# Mostrar los resultados de los ANOVA
print(f"ANOVA para FSH: F-statistic = {anova_fsh.statistic}, p-value = {anova_fsh.pvalue}")
print(f"ANOVA para LH: F-statistic = {anova_lh.statistic}, p-value = {anova_lh.pvalue}")
print(f"ANOVA para FSH/LH: F-statistic = {anova_fsh_lh.statistic}, p-value = {anova_fsh_lh.pvalue}")