# -*- coding: utf-8 -*-
"""Anova1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUYm-Yr42wefQiIhvZshN2qOHISfXr5C

# ANOVA 1: SÍNTOMAS vs HORMONAS
# Análisis Estadístico de Biomarcadores y Factores Asociados al SOP
# Equipo: Los SOP-timizadores


## OBJETIVO DEL ANÁLISIS ANOVA 1
Determinar si la presencia de síntomas clínicos (Pimples, Weight gain, Hair loss)
se asocia con diferencias significativas en los niveles hormonales (AMH, LH, FSH/LH ratio).

## ¿POR QUÉ ANOVA Y NO SOLO CHI-CUADRADO?
Chi-cuadrado nos dijo que los síntomas están ASOCIADOS con SOP (análisis previo).
Ahora queremos ir más profundo:
- ¿Los síntomas también se relacionan con ALTERACIONES HORMONALES específicas?
- ¿Cuánto difieren los niveles hormonales entre grupos?
- ¿Estas diferencias son clínicamente relevantes?

## PRUEBAS ESTADÍSTICAS QUE USAREMOS:

1️⃣ PRUEBA DE LEVENE
   - Verifica si los grupos tienen varianzas similares
   - ANOVA asume varianzas iguales (homocedasticidad)
   - Si falla: ANOVA puede dar resultados incorrectos

2️⃣ ANOVA DE UN FACTOR (F-test)
   - Compara las medias de dos grupos
   - Prueba si las diferencias son estadísticamente significativas
   - Da el p-valor para decidir sobre H0

3️⃣ ETA CUADRADO (η²)
   - Mide el TAMAÑO del efecto (no solo si existe)
   - Diferencia entre "significancia estadística" y "relevancia práctica"
   - Crucial para interpretación clínica

## JUSTIFICACIÓN CIENTÍFICA
- **Pimples vs AMH**: El acné puede estar relacionado con hiperandrogenismo,
  y AMH elevada es un marcador clave de SOP
- **Weight gain vs AMH**: Chi-cuadrado mostró la asociación MÁS fuerte (χ²=103.31),
  queremos validar si también hay diferencias hormonales
- **Hair loss vs FSH/LH ratio**: La alopecia androgenética puede relacionarse
  con desbalance FSH/LH característico de SOP
- **Pimples vs LH**: Los andrógenos (reflejados por LH alta) están directamente
  asociados con acné en mujeres con SOP

## HIPÓTESIS
H0: No hay diferencia significativa en los niveles hormonales entre grupos
    con y sin el síntoma
H1: Existe diferencia significativa en los niveles hormonales entre grupos
"""

import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import f_oneway, levene
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
ALPHA = 0.05

"""### Carga de datos"""

df = pd.read_csv('PCOS_data_1.csv')
df['FSH/LH'] = df['FSH(mIU/mL)'] / df['LH(mIU/mL)']
df['FSH/LH'] = df['FSH/LH'].replace([np.inf, -np.inf], np.nan)

print("="*70)
print("📊 DATASET CARGADO")
print("="*70)
print(f"Total registros: {len(df)}")
print(f"Mujeres con SOP: {df['PCOS (Y/N)'].sum()}")
print(f"Mujeres sin SOP: {len(df) - df['PCOS (Y/N)'].sum()}")

def obtener_grupos(df, sintoma_col, hormona_col):
    """Extrae y limpia los dos grupos a comparar"""
    datos = df[[sintoma_col, hormona_col]].dropna()
    grupo_si = datos[datos[sintoma_col] == 1][hormona_col]
    grupo_no = datos[datos[sintoma_col] == 0][hormona_col]
    return grupo_si, grupo_no

def estadisticas_descriptivas(grupo_si, grupo_no, sintoma, hormona):
    """Muestra estadísticas básicas de ambos grupos"""
    print(f"\n📊 ESTADÍSTICAS: {sintoma} vs {hormona}")
    print("-" * 70)
    print(f"CON síntoma:  n={len(grupo_si):3d} | Media={grupo_si.mean():7.3f} | DE={grupo_si.std():6.3f}")
    print(f"SIN síntoma:  n={len(grupo_no):3d} | Media={grupo_no.mean():7.3f} | DE={grupo_no.std():6.3f}")
    print(f"Diferencia:   {grupo_si.mean() - grupo_no.mean():+7.3f} ({abs((grupo_si.mean()-grupo_no.mean())/grupo_no.mean()*100):.1f}%)")

def prueba_levene(grupo_si, grupo_no):
    """Verifica homogeneidad de varianzas"""
    print(f"\n🔬 LEVENE (Homogeneidad de varianzas)")
    print("   • Si p≥0.05 → Varianzas iguales ✓ (ANOVA válido)")
    print("   • Si p<0.05 → Varianzas diferentes ⚠️ (precaución)")

    stat, p = levene(grupo_si, grupo_no)
    print(f"   Resultado: p={p:.4f} → {'✓ OK' if p >= ALPHA else '⚠️ PRECAUCIÓN'}")
    return p

def anova_test(grupo_si, grupo_no):
    """Realiza ANOVA y calcula tamaño del efecto"""
    print(f"\n📊 ANOVA (Comparación de medias)")

    # ANOVA
    f_stat, p_valor = f_oneway(grupo_si, grupo_no)

    # Eta cuadrado
    datos_completos = pd.concat([grupo_si, grupo_no])
    media_total = datos_completos.mean()
    ssb = len(grupo_si)*(grupo_si.mean()-media_total)**2 + len(grupo_no)*(grupo_no.mean()-media_total)**2
    sst = ((datos_completos - media_total)**2).sum()
    eta2 = ssb / sst

    print(f"   F={f_stat:.3f} | p={p_valor:.4e}")
    print(f"   Eta²={eta2:.4f} ({'Pequeño' if eta2<0.01 else 'Mediano' if eta2<0.06 else 'Grande'})")

    # Decisión
    if p_valor < ALPHA:
        print(f"   ✓ SIGNIFICATIVO (p<0.05) → Hay diferencia real")
    else:
        print(f"   ✗ NO significativo (p≥0.05) → Sin evidencia de diferencia")

    return f_stat, p_valor, eta2

def visualizar(grupo_si, grupo_no, sintoma, hormona, p_valor):
    """Crea visualizaciones compactas"""
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    # Boxplot
    datos = pd.DataFrame({
        'Grupo': ['Sí']*len(grupo_si) + ['No']*len(grupo_no),
        hormona: list(grupo_si) + list(grupo_no)
    })
    sns.boxplot(data=datos, x='Grupo', y=hormona, ax=axes[0], palette=['#FF6B6B','#4ECDC4'])
    axes[0].set_title(f'{sintoma} vs {hormona}', fontweight='bold')

    # Anotación p-valor
    y_max = datos[hormona].max()
    texto_p = f"p={'<0.001***' if p_valor<0.001 else f'{p_valor:.3f}' + ('**' if p_valor<0.01 else '*' if p_valor<0.05 else ' ns')}"
    axes[0].text(0.5, y_max*1.05, texto_p, ha='center', fontweight='bold',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    # Histograma
    axes[1].hist(grupo_si, bins=15, alpha=0.6, label='Con síntoma', color='#FF6B6B', edgecolor='black')
    axes[1].hist(grupo_no, bins=15, alpha=0.6, label='Sin síntoma', color='#4ECDC4', edgecolor='black')
    axes[1].axvline(grupo_si.mean(), color='red', linestyle='--', linewidth=2)
    axes[1].axvline(grupo_no.mean(), color='blue', linestyle='--', linewidth=2)
    axes[1].set_xlabel(hormona, fontweight='bold')
    axes[1].set_title('Distribución comparativa', fontweight='bold')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

def analizar_anova(df, sintoma_col, hormona_col, titulo, justificacion):
    """Función principal que ejecuta análisis completo"""
    print("\n\n" + "="*70)
    print(f"🔬 {titulo}")
    print("="*70)
    print(f"💡 {justificacion}\n")

    # 1. Obtener datos
    grupo_si, grupo_no = obtener_grupos(df, sintoma_col, hormona_col)

    # 2. Estadísticas descriptivas
    estadisticas_descriptivas(grupo_si, grupo_no, sintoma_col, hormona_col)

    # 3. Prueba de Levene
    levene_p = prueba_levene(grupo_si, grupo_no)

    # 4. ANOVA
    f_stat, p_valor, eta2 = anova_test(grupo_si, grupo_no)

    # 5. Visualización
    visualizar(grupo_si, grupo_no, sintoma_col, hormona_col, p_valor)

    return {
        'sintoma': sintoma_col,
        'hormona': hormona_col,
        'n_si': len(grupo_si),
        'n_no': len(grupo_no),
        'media_si': grupo_si.mean(),
        'media_no': grupo_no.mean(),
        'f_stat': f_stat,
        'p_valor': p_valor,
        'eta2': eta2,
        'levene_p': levene_p,
        'significativo': p_valor < ALPHA
    }

resultados = []

# ANÁLISIS 1: Pimples vs AMH
resultados.append(analizar_anova(
    df, 'Pimples(Y/N)', 'AMH(ng/mL)',
    titulo="ANÁLISIS 1: PIMPLES (Acné) vs AMH",
    justificacion="""El acné en mujeres con SOP está relacionado con hiperandrogenismo.
    AMH (Hormona Anti-Mülleriana) es un marcador clave de reserva ovárica y está
    elevada en SOP debido a la acumulación de folículos antrales pequeños. Queremos
    determinar si las mujeres con acné tienen niveles de AMH significativamente
    diferentes, lo que sugeriría una relación entre manifestaciones cutáneas y
    disfunción ovárica."""
))

# ANÁLISIS 2: Weight Gain vs AMH
resultados.append(analizar_anova(
    df, 'Weight gain(Y/N)', 'AMH(ng/mL)',
    titulo="ANÁLISIS 2: WEIGHT GAIN (Ganancia de peso) vs AMH",
    justificacion="""La prueba de Chi-cuadrado reveló que Weight Gain tiene la asociación
    MÁS FUERTE con SOP (χ²=103.31, p<0.001). Ahora queremos confirmar si esta
    asociación también se refleja en diferencias hormonales específicas (AMH).
    La resistencia a la insulina, común en SOP, conduce tanto al aumento de peso
    como a alteraciones en la función ovárica, lo que podría explicar niveles
    elevados de AMH en pacientes con ganancia de peso."""
))

# ANÁLISIS 3: Hair Loss vs FSH/LH
resultados.append(analizar_anova(
    df, 'Hair loss(Y/N)', 'FSH/LH',
    titulo="ANÁLISIS 3: HAIR LOSS (Pérdida de cabello) vs FSH/LH Ratio",
    justificacion="""La alopecia androgenética en mujeres con SOP está relacionada con
    el desbalance hormonal característico del síndrome. En SOP, el ratio FSH/LH
    típicamente es bajo (< 1) debido a niveles elevados de LH. La pérdida de cabello
    puede ser una manifestación externa de este desbalance hormonal. Evaluamos si
    las mujeres con alopecia presentan un ratio FSH/LH significativamente más bajo,
    lo que indicaría una relación directa entre pérdida capilar y disfunción del
    eje hipotálamo-hipófisis-ovario."""
))

# ANÁLISIS 4: Pimples vs LH
resultados.append(analizar_anova(
    df, 'Pimples(Y/N)', 'LH(mIU/mL)',
    titulo="ANÁLISIS 4: PIMPLES (Acné) vs LH",
    justificacion="""LH (Hormona Luteinizante) elevada estimula la producción de andrógenos
    (principalmente testosterona) en las células tecales del ovario. Estos andrógenos
    son los responsables DIRECTOS del acné en mujeres con SOP al estimular las
    glándulas sebáceas. Esperamos encontrar niveles de LH significativamente más
    altos en mujeres con acné, lo que confirmaría el mecanismo fisiopatológico:
    LH elevada → hiperandrogenismo → manifestaciones cutáneas (acné)."""
))

print("\n\n" + "="*70)
print("📋 TABLA RESUMEN - ANOVA 1: SÍNTOMAS vs HORMONAS")
print("="*70)

resumen = pd.DataFrame({
    'Síntoma': [r['sintoma'] for r in resultados],
    'Hormona': [r['hormona'] for r in resultados],
    'n_Con': [r['n_si'] for r in resultados],
    'n_Sin': [r['n_no'] for r in resultados],
    'Media_Con': [f"{r['media_si']:.3f}" for r in resultados],
    'Media_Sin': [f"{r['media_no']:.3f}" for r in resultados],
    'F': [f"{r['f_stat']:.2f}" for r in resultados],
    'p-valor': [f"{r['p_valor']:.4e}" for r in resultados],
    'η²': [f"{r['eta2']:.4f}" for r in resultados],
    'Signif.': ['✓' if r['significativo'] else '✗' for r in resultados]
})

print("\n", resumen.to_string(index=False))

# CONCLUSIONES
print("\n" + "="*70)
print("🎯 CONCLUSIONES FINALES")
print("="*70)

significativos = [r for r in resultados if r['significativo']]
print(f"\n✓ Análisis significativos: {len(significativos)}/4")

if significativos:
    print("\n📊 HALLAZGOS CLAVE:")
    for r in significativos:
        diff = r['media_si'] - r['media_no']
        print(f"\n• {r['sintoma']} → {r['hormona']}")
        print(f"  Diferencia: {diff:+.3f} | η²={r['eta2']:.4f} | p={r['p_valor']:.4e}")

print("\n" + "="*70)
print("✅ ANOVA 1 COMPLETADO | Fecha: 3-Nov-2024 | Responsable: Paul")
print("="*70)