# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWr3ECOcYruoat54qhiXEV7KopLcPze8
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Cargar datos
df = pd.read_excel("/content/PCOS_data_1 (1).xlsx")

# 2. Renombrar columnas a algo más cómodo
df = df.rename(columns={
    'PCOS (Y/N)': 'PCOS',
    'BMI': 'IMC',
    'AMH(ng/mL)': 'AMH',
    'FSH/LH': 'FSH_LH'
})

# 3. Crear variable de grupo legible
df['Grupo'] = df['PCOS'].map({0: 'No PCOS', 1: 'PCOS'})

# ------------ BOXPLOT AMH POR GRUPO ------------
plt.figure()
amh_no = df[df['Grupo'] == 'No PCOS']['AMH'].dropna()
amh_si = df[df['Grupo'] == 'PCOS']['AMH'].dropna()

plt.boxplot([amh_no, amh_si],
            labels=['No PCOS', 'PCOS'])

plt.ylabel('AMH (ng/mL)')
plt.title('AMH por grupo')
plt.show()

# ------------ BOXPLOT FSH/LH POR GRUPO ------------
plt.figure()
ratio_no = df[df['Grupo'] == 'No PCOS']['FSH_LH'].dropna()
ratio_si = df[df['Grupo'] == 'PCOS']['FSH_LH'].dropna()

plt.boxplot([ratio_no, ratio_si],
            labels=['No PCOS', 'PCOS'])

plt.ylabel('Relación FSH/LH')
plt.title('FSH/LH por grupo')
plt.show()

# ------------ HISTOGRAMA IMC ------------
plt.figure()
plt.hist(df['IMC'].dropna(),
         bins=15,
         edgecolor='black')

plt.xlabel('IMC')
plt.ylabel('Frecuencia')
plt.title('Distribución de IMC')
plt.show()

"""1. Boxplot de AMH por grupo (PCOS vs No PCOS)

Este gráfico muestra que los niveles de AMH son más bajos en personas con PCOS comparado con quienes no tienen la condición. Aunque el grupo sin PCOS tiene una mayor variabilidad, los valores atípicos en el grupo de PCOS sugieren algunos casos extremos.

2. Boxplot de FSH/LH por grupo (PCOS vs No PCOS)

En las personas con PCOS, la relación FSH/LH es significativamente más alta que en el grupo sin PCOS, lo que refleja el desbalance hormonal característico del síndrome. Los valores atípicos en ambos grupos indican algunas variaciones extremas.

3. Histograma de IMC (Índice de Masa Corporal)

El histograma revela que la mayoría de las personas tienen un IMC entre 22 y 28, lo que indica sobrepeso. Aunque hay algunas personas con obesidad, la mayoría se encuentra en un rango moderado de IMC, lo cual puede estar relacionado con el PCOS.
"""