# -*- coding: utf-8 -*-
"""Chi_cuadrada1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4Fvga2cBq3RpFrxktnCuDUeh8B_1dhI

**CHI CUADRADA** **(** $x^2$ **)**

Pruebas de Chi-cuadrado: Asociación entre SOP y cada síntoma/clínica (Hair loss,
Pimples, Weight gain)
"""

import pandas as pd
from scipy.stats import chi2_contingency

# --- Configuración ---
archivo_excel = "pso.xlsx"
variable_principal = 'PCOS (Y/N)'
lista_sintomas = ['Weight gain(Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)']
alpha = 0.05  # Nivel de significancia estándar

# --- Carga de datos ---
try:
    df = pd.read_excel(archivo_excel)

    print("--- INICIO DEL PROCEDIMIENTO DE CHI-CUADRADO ---")

    # Bucle para analizar cada síntoma contra la variable principal (SOP)
    for sintoma in lista_sintomas:

        print(f"\n=================================================")
        print(f"  Análisis de Asociación: SOP vs. {sintoma}")
        print(f"=================================================")


        tabla_contingencia = pd.crosstab(df[variable_principal], df[sintoma])

        chi2_stat, p_valor, gl, frec_esperadas = chi2_contingency(tabla_contingencia)

        # --- PASO 3: Reportar los valores clave ---
        print("\n  Resultados Estadísticos Obtenidos:")
        print(f"  Estadístico Chi-cuadrado (χ²): {chi2_stat:.4f}")
        print(f"  Grados de Libertad (gl):      {gl}")
        print(f"  Valor p (p-value):            {p_valor:.4e}") # Notación científica (ej. 9.80e-14)


        print("\n  Procedimiento de Decisión (La 'Comparativa <'):")
        print(f"  Se compara el Valor p ({p_valor:.4e}) con alpha ({alpha})")

        if p_valor < alpha:
            # Si el valor p es menor que alpha...
            print("  Resultado: VERDADERO (p < alpha)")
            print("  Conclusión: Se rechaza la hipótesis nula.")
            print("  Interpretación: Existe una asociación estadísticamente SIGNIFICATIVA.")
        else:
            # Si el valor p es mayor o igual que alpha...
            print("  Resultado: FALSO (p >= alpha)")
            print("  Conclusión: No se puede rechazar la hipótesis nula.")
            print("  Interpretación: NO hay evidencia de una asociación estadísticamente significativa.")

except FileNotFoundError:
    print(f"Error: No se pudo encontrar el archivo '{archivo_csv}'")
except KeyError as e:
    print(f"Error: No se encontró la columna {e}. Revisa los nombres en tu CSV.")

print("\n--- FIN DEL PROCEDIMIENTO ---")