# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Kc7M10mMlKwUe3b8EONIiCY_lDC6VOo
"""

import pandas as pd
try:
    df = pd.read_excel("PCOS_data_1.xlsx")
except FileNotFoundError:
    print("Error: No se encontró el archivo. Revisa el nombre.")
    exit()

df.columns = df.columns.str.strip()
df["FSH/LH"] = pd.to_numeric(df["FSH/LH"], errors='coerce')

# --- Definir las condiciones base ---
es_sop = (df["PCOS (Y/N)"] == 1)
tiene_pimples = (df["Pimples(Y/N)"] == 1)
ratio_bajo = (df["FSH/LH"] < 1)
pierde_cabello = (df["Hair loss(Y/N)"] == 1)
gana_peso = (df["Weight gain(Y/N)"] == 1)

# --- Contar los totales (denominadores) ---
total_con_sop = es_sop.sum()
total_con_pimples = tiene_pimples.sum()
total_con_ratio_bajo = ratio_bajo.sum()
total_pierde_cabello = pierde_cabello.sum()
total_gana_peso = gana_peso.sum()

# --- Contar las intersecciones (numeradores) ---
sop_y_pimples = (es_sop & tiene_pimples).sum()
sop_y_ratio_bajo = (es_sop & ratio_bajo).sum()
sop_y_pierde_cabello = (es_sop & pierde_cabello).sum()
sop_y_gana_peso = (es_sop & gana_peso).sum()


# --- 1. Probabilidades de TENER SOP (dado un síntoma) ---
print("--- Probabilidades de TENER SOP (P(SOP | Síntoma)) ---")

prob_1 = sop_y_pimples / total_con_pimples
print(f"P(SOP | Pimples=Si) = {prob_1:.2%}")

prob_2 = sop_y_ratio_bajo / total_con_ratio_bajo
print(f"P(SOP | FSH/LH < 1) = {prob_2:.2%}")

prob_3 = sop_y_gana_peso / total_gana_peso
print(f"P(SOP | Weight gain=Si) = {prob_3:.2%}")

prob_4 = sop_y_pierde_cabello / total_pierde_cabello
print(f"P(SOP | Hair loss=Si) = {prob_4:.2%}\n")


# --- 2. Probabilidades de TENER SÍNTOMAS (dado que ya se tiene SOP) ---
print("--- Probabilidades de TENER SÍNTOMAS (P(Síntoma | SOP)) ---")

prob_inv_1 = sop_y_pimples / total_con_sop
print(f"P(Pimples=Si | SOP=Si) = {prob_inv_1:.2%}")

prob_inv_2 = sop_y_ratio_bajo / total_con_sop
print(f"P(FSH/LH < 1 | SOP=Si) = {prob_inv_2:.2%}")

prob_inv_3 = sop_y_gana_peso / total_con_sop
print(f"P(Weight gain=Si | SOP=Si) = {prob_inv_3:.2%}")

prob_inv_4 = sop_y_pierde_cabello / total_con_sop
print(f"P(Hair loss=Si | SOP=Si) = {prob_inv_4:.2%}")

"""Acné (Pimples):$P(\text{SOP} | \text{Pimples}) = 58.43\%$: Si una paciente llega con acné, tiene una probabilidad del 58.43% de tener SOP (según tus datos).$P(\text{Pimples} | \text{SOP}) = 54.80\%$: De todas las pacientes que ya sabemos que tienen SOP, solo el 54.80% reporta tener acné.Conclusión: El acné es un indicador moderadamente bueno en ambos sentidos.

Ratio FSH/LH < 1:$P(\text{SOP} | \text{Ratio} < 1) = 70.08\%$: ¡Este es un indicador fuerte! Si ves un ratio bajo, hay una alta probabilidad (70%) de que la paciente tenga SOP. Es un buen indicador de diagnóstico.$P(\text{Ratio} < 1 | \text{SOP}) = 50.28\%$: Esto es muy revelador. De todas las pacientes con SOP, solo la mitad (50.28%) tiene este ratio bajo.Conclusión: El ratio bajo es un excelente indicador para sospechar SOP, pero la ausencia de un ratio bajo no descarta el SOP, ya que la mitad de las pacientes con SOP no lo presentan.


Weight Gain (Aumento de peso):$P(\text{SOP} | \text{Weight gain}) = 50.73\%$: Si una persona aumentó de peso, la probabilidad de que tenga SOP es de aprox. 51% (es como lanzar una moneda). No es un predictor muy fuerte por sí solo.$P(\text{Weight gain} | \text{SOP}) = 58.76\%$: Sin embargo, de las pacientes que tienen SOP, casi el 59% reporta aumento de peso. Es un síntoma común dentro del grupo de SOP.

Hair Loss (Pérdida de cabello):$P(\text{SOP} | \text{Hair loss}) = 46.96\%$: Este es el predictor más débil hasta ahora. Si una persona tiene pérdida de cabello, es ligeramente menos probable que tenga SOP que lo contrario.$P(\text{Hair loss} | \text{SOP}) = 65.54\%$: ¡Pero mira esto! Es el síntoma más común entre las pacientes que ya tienen SOP (casi 2 de cada 3 lo reportan).
"""